git:
  depth: 10

os:
  - osx

osx_image: xcode7.3
language: objective-c
compiler: clang
sudo: false

env:
  global:
    - SIGN_DARWIN_KEYCHAIN_NAME=travis.keychain
    - SIGN_DARWIN_KEYCHAIN_PASSWORD=travis

install:
  - export PR=https://api.github.com/repos/$TRAVIS_REPO_SLUG/pulls/$TRAVIS_PULL_REQUEST
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo `curl -s $PR | jq -r .head.ref`; fi)
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"
  - git clone https://github.com/creationix/nvm.git /tmp/.nvm
  - source /tmp/.nvm/nvm.sh
  - nvm install 0.12
  - nvm use 0.12
  - npm install -g gulp
  - npm install --only=dev
  - if [[ $BRANCH == 'staging' || $BRANCH == 'deploy' ]]; then npm install; fi
  - if [[ $BRANCH == 'staging' || $BRANCH == 'deploy' ]]; then ./scripts/darwin/install_aws.sh; fi
  - if [[ $BRANCH == 'staging' || $BRANCH == 'deploy' ]]; then ./scripts/darwin/rebuild_src.sh; fi

before_script:
  - npm test

script:
  - if [[ $BRANCH == 'staging' ]]; then ./scripts/darwin/build_staging.sh; fi
  - if [[ $BRANCH == 'deploy' ]]; then ./scripts/darwin/build_deploy.sh; fi

cache:
  directories:
    - node_modules
    - src/node_modules
    - cache

notifications:
  email: false
  webhooks:
    - https://webhooks.gitter.im/e/2c65a3d61901add4556f
