git:
  depth: 10

os:
  - osx

osx_image: xcode7.3
language: objective-c
compiler: clang
sudo: false

env:
  global:
    - SIGN_DARWIN_KEYCHAIN_NAME=travis.keychain
    - SIGN_DARWIN_KEYCHAIN_PASSWORD=travis

install:
  - echo $TRAVIS_BRANCH
  - ./scripts/install_nvm.sh
  - npm install -g gulp
  - npm install --only=dev
  - if [[ $TRAVIS_BRANCH == 'staging' || $TRAVIS_BRANCH == 'deploy' ]]; then npm install; fi
  - if [[ $TRAVIS_BRANCH == 'staging' || $TRAVIS_BRANCH == 'deploy' ]]; then ./scripts/darwin/install_aws.sh; fi
  - if [[ $TRAVIS_BRANCH == 'staging' || $TRAVIS_BRANCH == 'deploy' ]]; then ./scripts/darwin/rebuild_src.sh; fi

before_script:
  - npm test

script:
  - npm test
  - if [[ $TRAVIS_BRANCH == 'staging' ]]; then ./scripts/darwin/build_staging.sh; fi
  - if [[ $TRAVIS_BRANCH == 'deploy' ]]; then ./scripts/darwin/build_deploy.sh; fi

cache:
  directories:
    - node_modules
    - src/node_modules
    - cache

notifications:
  email: false
  webhooks:
    - https://webhooks.gitter.im/e/2c65a3d61901add4556f
