clone_depth: 10
skip_tags: true

init:
  - git config --global core.autocrlf input

environment:
  SIGNTOOL_PATH: 'C:/Program Files (x86)/Microsoft SDKs/Windows/v7.1A/Bin/SignTool.exe'
  SIGN_WIN_CERTIFICATE_FILE: 'C:/foss_ar_sha2.pfx'
  SIGN_WIN_CERTIFICATE_PASSWORD:
    secure: jZHktkydPALqcwx36cBY1g==
  AWS_ACCESS_KEY_ID:
    secure: un4e1Apf/PIHv/duLtXtk4j4AIgorOKxvMhxhoUd4N8=
  AWS_SECRET_ACCESS_KEY:
    secure: zP4aGkRtRqZIKZ2tM2q//6dC4SfzKdxDBGTSV3AEbpUnDDco/uMy9ZU1cmVEQigk
  GITHUB_TOKEN:
    secure: VgebEox3uOMipNS2O/GeWXLpfqPcIp3hUstSLsaL0YpHvxG95FVzQLuI3IbahvFH
  SENTRY_DSN_PRIVATE:
    secure: T+ibuaoG5w3bUZWFzx3YDty9ALmIehh7hj4tD4+JGJ19GezaSGAah/x+tBM43Cyor+X4g6hnjBIGFpI9Qhl7bA0C37ulyCQ19U5wcIAMvYaQF03dYYolN6hcea1fmU20
  PIWIK_SERVER_URL:
    secure: OSFCKJBPssEPIO/kA78OTi+CZire5JtvpTi9fr+7jWg=
  SQUIRREL_UPDATES_URL:
    secure: BNlChGRei/OKFGO3EQIc2yvv8HT9eN/6P0gZPShaoD0=

cache:
  - "node_modules -> package.json"
  - "src\\node_modules -> src\\package.json"
  - "cache -> src\\package.json"
  - "%APPDATA%\\npm-cache"

install:
  - npm install -g npm@2
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install -g gulp
  - npm install --only=dev

test_script:
  - npm test

deploy_script:
  - IF APPVEYOR_REPO_BRANCH == "staging" scripts/win32/build_staging.cmd
  - IF APPVEYOR_REPO_BRANCH == "deploy" scripts/win32/build_deploy.cmd

notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/676ac0f0c100c8d70e7c
